# Generated by Django 4.2.4 on 2023-08-31 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
                ('url', models.TextField(max_length=1000, null=True)),
                ('urlToImage', models.CharField(max_length=500, null=True)),
                ('publishedAt', models.DateTimeField(null=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
